<?php
/**
 * @category   Grc
 * @package    Grc_Corporatetraining
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Grc\Corporatetraining\Controller\Index;

use Magento\Framework\App\Action\Context;
use Grc\Corporatetraining\Model\CorporatetrainingFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Corporatetraining
     */
    protected $_corporatetraining;

    public function __construct(
		Context $context,
        CorporatetrainingFactory $corporatetraining
    ) {
        $this->_corporatetraining = $corporatetraining;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$corporatetraining = $this->_corporatetraining->create();
        $corporatetraining->setData($data);
        if($corporatetraining->save()){
            $this->messageManager->addSuccessMessage(__('You have successfully registered for Corporate Training.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('');
        return $resultRedirect;
    }
}
